/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/clouds2.glb");
  const [material, setMaterial] = useState();
  const groupRef = useRef();

  useFrame(({ clock }) => {
    const elapsedTime = clock.getElapsedTime();
    if (groupRef.current) {
      groupRef.current.position.x = Math.sin(elapsedTime * 0.2) * 10;
    }
  });

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials.Material}
        position={[10.218, 0.915, 0]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials.Material}
        position={[21.227, 2.015, -3.831]}
        scale={[1, 0.903, 1]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials.Material}
        position={[4.822, 1.041, -9.869]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.405, -0.366, -0.405]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials.Material}
        position={[20.952, 1.467, -1.194]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials.Material}
        position={[4.934, 0.569, -7.37]}
        rotation={[0, -0.083, -Math.PI]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials.Material}
        position={[15.796, 3.95, -6.114]}
        rotation={[0, -0.083, -Math.PI]}
        scale={[-0.345, -0.197, -0.219]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials.Material}
        position={[-25.89, 2.015, -4.451]}
        rotation={[-Math.PI, 0.004, -Math.PI]}
        scale={[0.928, 0.749, 0.841]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials.Material}
        position={[-14.656, 1.398, -2.7]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials.Material}
        position={[-19.812, 3.881, -7.619]}
        rotation={[0, -0.083, -Math.PI]}
        scale={[-0.345, -0.197, -0.219]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials.Material}
        position={[-3.29, 2.833, -8.775]}
        scale={[0.418, 0.319, 0.336]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials.Material}
        position={[-3.998, 2.536, -7.254]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.238, -0.19, -0.182]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials.Material}
        position={[-12.644, 3.638, -11.893]}
        scale={[0.337, 0.197, 0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials.Material}
        position={[-15.055, 4.15, -13.89]}
        scale={[0.337, 0.197, 0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials.Material}
        position={[-7.129, 2.115, -7.092]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.149, -0.134, -0.149]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials.Material}
        position={[-9.441, 4.623, -18.974]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.249, -0.101, -0.149]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube016.geometry}
        material={materials.Material}
        position={[24.752, 3.38, -7.511]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.418, -0.319, -0.336]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube017.geometry}
        material={materials.Material}
        position={[21.401, 4.8, -15.672]}
        scale={[0.55, 0.146, 0.162]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube018.geometry}
        material={materials.Material}
        position={[22.621, 4.97, -16.496]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.296, -0.079, -0.087]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube019.geometry}
        material={materials.Material}
        position={[79.825, 0.915, 17.3]}
        rotation={[0, -0.517, 0]}
        scale={[1, 0.766, 1]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube021.geometry}
        material={materials.Material}
        position={[85.065, 1.561, 18.93]}
        rotation={[-Math.PI, 0.632, 0]}
        scale={[-0.405, -0.366, -0.405]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube022.geometry}
        material={materials.Material}
        position={[89.941, 1.467, 23.734]}
        rotation={[-Math.PI, 0.632, 0]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube023.geometry}
        material={materials.Material}
        position={[84.279, 0.569, 24.471]}
        rotation={[0, -0.715, -Math.PI]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube024.geometry}
        material={materials.Material}
        position={[90.705, 3.95, 27.97]}
        rotation={[0, -0.76, -Math.PI]}
        scale={[-0.345, -0.197, -0.219]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube025.geometry}
        material={materials.Material}
        position={[36.638, 2.015, -3.21]}
        rotation={[-Math.PI, 0.353, -Math.PI]}
        scale={[0.928, 0.749, 0.841]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube026.geometry}
        material={materials.Material}
        position={[57.376, 1.398, 8.898]}
        rotation={[-Math.PI, 0.348, 0]}
        scale={[-0.335, -0.302, -0.335]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube027.geometry}
        material={materials.Material}
        position={[54.208, 3.881, 2.514]}
        rotation={[0, -0.431, -Math.PI]}
        scale={[-0.563, -0.322, -0.358]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube028.geometry}
        material={materials.Material}
        position={[71.842, 2.833, 5.711]}
        rotation={[0, -0.348, 0]}
        scale={[0.94, 0.717, 0.756]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube029.geometry}
        material={materials.Material}
        position={[68.948, 1.997, 8.254]}
        rotation={[-Math.PI, 0.348, 0]}
        scale={[-0.238, -0.19, -0.182]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube030.geometry}
        material={materials.Material}
        position={[62.405, 3.638, 0.944]}
        rotation={[0, -0.348, 0]}
        scale={[0.267, 0.156, 0.173]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube032.geometry}
        material={materials.Material}
        position={[65.95, 1.645, 7.338]}
        rotation={[-Math.PI, 0.348, 0]}
        scale={[-0.149, -0.134, -0.149]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube033.geometry}
        material={materials.Material}
        position={[58.347, 4.22, -2.016]}
        rotation={[-Math.PI, 0.348, 0]}
        scale={[-0.249, -0.101, -0.149]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube034.geometry}
        material={materials.Material}
        position={[96.06, 3.38, 17.824]}
        rotation={[-Math.PI, 0.804, 0]}
        scale={[-0.418, -0.319, -0.336]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube035.geometry}
        material={materials.Material}
        position={[67.222, 4.8, 26.229]}
        rotation={[0, -0.549, 0]}
        scale={[0.55, 0.146, 0.162]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube036.geometry}
        material={materials.Material}
        position={[68.692, 4.97, 26.164]}
        rotation={[-Math.PI, 0.549, 0]}
        scale={[-0.296, -0.079, -0.087]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube038.geometry}
        material={materials.Material}
        position={[84.279, 2.015, 63.562]}
        rotation={[Math.PI, -1.077, Math.PI]}
        scale={[1, 0.903, 1]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube039.geometry}
        material={materials.Material}
        position={[85.675, 3.2, 68.421]}
        rotation={[0, 0.957, -Math.PI]}
        scale={[-0.405, -0.366, -0.405]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube040.geometry}
        material={materials.Material}
        position={[84.406, 1.467, 72.721]}
        rotation={[0, 0.957, -Math.PI]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube041.geometry}
        material={materials.Material}
        position={[83.567, 0.569, 67.073]}
        rotation={[Math.PI, -0.874, 0]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube042.geometry}
        material={materials.Material}
        position={[91.539, 3.95, 48.935]}
        rotation={[Math.PI, -1.538, 0]}
        scale={[-0.345, -0.197, -0.219]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube043.geometry}
        material={materials.Material}
        position={[88.942, 2.015, 32.704]}
        rotation={[-Math.PI, 1.525, -Math.PI]}
        scale={[0.928, 0.749, 0.841]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube044.geometry}
        material={materials.Material}
        position={[93.477, 1.398, 40.505]}
        rotation={[-Math.PI, 1.521, 0]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube045.geometry}
        material={materials.Material}
        position={[98.133, 3.881, 35.11]}
        rotation={[Math.PI, -1.538, 0]}
        scale={[-0.345, -0.197, -0.219]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube046.geometry}
        material={materials.Material}
        position={[100.112, 2.833, 51.554]}
        rotation={[0, -1.521, 0]}
        scale={[0.418, 0.319, 0.336]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube047.geometry}
        material={materials.Material}
        position={[98.558, 2.536, 50.923]}
        rotation={[-Math.PI, 1.521, 0]}
        scale={[-0.238, -0.19, -0.182]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube048.geometry}
        material={materials.Material}
        position={[102.759, 3.638, 42.057]}
        rotation={[0, -1.521, 0]}
        scale={[0.337, 0.197, 0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube049.geometry}
        material={materials.Material}
        position={[104.633, 4.15, 39.549]}
        rotation={[0, -1.521, 0]}
        scale={[0.337, 0.197, 0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube050.geometry}
        material={materials.Material}
        position={[98.239, 2.115, 47.804]}
        rotation={[-Math.PI, 1.521, 0]}
        scale={[-0.149, -0.134, -0.149]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube051.geometry}
        material={materials.Material}
        position={[109.991, 4.623, 44.902]}
        rotation={[-Math.PI, 1.521, 0]}
        scale={[-0.249, -0.101, -0.149]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube052.geometry}
        material={materials.Material}
        position={[87.823, 3.51, 51.224]}
        rotation={[-Math.PI, 1.521, 0]}
        scale={[-0.418, -0.319, -0.336]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube053.geometry}
        material={materials.Material}
        position={[91.282, 4.8, 70.91]}
        rotation={[Math.PI, -1.286, Math.PI]}
        scale={[0.55, 0.146, 0.162]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube054.geometry}
        material={materials.Material}
        position={[91.729, 4.97, 72.313]}
        rotation={[0, 1.286, -Math.PI]}
        scale={[-0.296, -0.079, -0.087]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube056.geometry}
        material={materials.Material}
        position={[49.02, 1.681, 93.373]}
        rotation={[-Math.PI, 0.362, -Math.PI]}
        scale={[1.339, 0.903, 1.083]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube057.geometry}
        material={materials.Material}
        position={[40.507, 2.976, 92.159]}
        rotation={[0, 0.209, -Math.PI]}
        scale={[-0.405, -0.366, -0.405]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube058.geometry}
        material={materials.Material}
        position={[36.652, 1.999, 94.447]}
        rotation={[0, 0.209, -Math.PI]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube059.geometry}
        material={materials.Material}
        position={[39.879, 0.569, 89.737]}
        rotation={[Math.PI, -0.126, 0]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube060.geometry}
        material={materials.Material}
        position={[43.878, 3.95, 92.65]}
        rotation={[Math.PI, -0.353, 0]}
        scale={[-0.345, -0.197, -0.219]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube061.geometry}
        material={materials.Material}
        position={[80.955, 2.015, 73.524]}
        rotation={[0, 0.432, 0]}
        scale={[0.928, 0.749, 0.841]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube062.geometry}
        material={materials.Material}
        position={[70.033, 1.398, 76.685]}
        rotation={[0, 0.436, -Math.PI]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube063.geometry}
        material={materials.Material}
        position={[76.786, 3.881, 78.964]}
        rotation={[Math.PI, -0.353, 0]}
        scale={[-0.345, -0.197, -0.219]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube064.geometry}
        material={materials.Material}
        position={[62.3, 2.833, 86.994]}
        rotation={[Math.PI, -0.436, Math.PI]}
        scale={[0.418, 0.319, 0.336]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube065.geometry}
        material={materials.Material}
        position={[62.299, 2.536, 85.317]}
        rotation={[0, 0.436, -Math.PI]}
        scale={[-0.238, -0.19, -0.182]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube066.geometry}
        material={materials.Material}
        position={[72.095, 3.638, 85.867]}
        rotation={[Math.PI, -0.436, Math.PI]}
        scale={[0.337, 0.197, 0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube067.geometry}
        material={materials.Material}
        position={[75.124, 4.15, 86.658]}
        rotation={[Math.PI, -0.436, Math.PI]}
        scale={[0.337, 0.197, 0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube068.geometry}
        material={materials.Material}
        position={[65.068, 3.985, 83.847]}
        rotation={[0, 0.436, -Math.PI]}
        scale={[-0.149, -0.134, -0.149]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube069.geometry}
        material={materials.Material}
        position={[72.185, 4.623, 93.638]}
        rotation={[0, 0.436, -Math.PI]}
        scale={[-0.249, -0.101, -0.149]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube070.geometry}
        material={materials.Material}
        position={[36.352, 3.38, 97.701]}
        rotation={[0, 0.436, -Math.PI]}
        scale={[-0.418, -0.319, -0.336]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube071.geometry}
        material={materials.Material}
        position={[27.638, 4.8, 93.228]}
        rotation={[Math.PI, -0.168, Math.PI]}
        scale={[0.55, 0.146, 0.162]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube072.geometry}
        material={materials.Material}
        position={[26.572, 4.97, 94.243]}
        rotation={[0, 0.168, -Math.PI]}
        scale={[-0.296, -0.079, -0.087]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube073.geometry}
        material={materials.Material}
        position={[-19.494, 1.322, 90.638]}
        rotation={[Math.PI, -0.09, Math.PI]}
        scale={[1.628, 1, 1.007]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube075.geometry}
        material={materials.Material}
        position={[-21.043, 2.561, 91.14]}
        rotation={[0, 0.09, -Math.PI]}
        scale={[-0.405, -0.366, -0.405]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube076.geometry}
        material={materials.Material}
        position={[-27.103, 1.467, 92.798]}
        rotation={[0, 0.09, -Math.PI]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube078.geometry}
        material={materials.Material}
        position={[-28.985, 3.95, 85.468]}
        rotation={[-Math.PI, 0.392, 0]}
        scale={[-0.345, -0.197, -0.219]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube079.geometry}
        material={materials.Material}
        position={[19.843, 2.015, 91.849]}
        rotation={[0, 0.085, 0]}
        scale={[0.928, 0.749, 0.841]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube080.geometry}
        material={materials.Material}
        position={[8.498, 1.398, 91.11]}
        rotation={[0, 0.09, -Math.PI]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube081.geometry}
        material={materials.Material}
        position={[14.073, 3.881, 95.548]}
        rotation={[Math.PI, -0.007, 0]}
        scale={[-0.345, -0.197, -0.219]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube082.geometry}
        material={materials.Material}
        position={[-6.146, 2.833, 93.515]}
        rotation={[Math.PI, -0.09, Math.PI]}
        scale={[0.418, 0.319, 0.336]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube083.geometry}
        material={materials.Material}
        position={[-5.577, 2.536, 91.937]}
        rotation={[0, 0.09, -Math.PI]}
        scale={[-0.238, -0.19, -0.182]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube084.geometry}
        material={materials.Material}
        position={[4.587, 3.638, 94.077]}
        rotation={[Math.PI, -0.09, Math.PI]}
        scale={[0.337, 0.197, 0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube085.geometry}
        material={materials.Material}
        position={[7.167, 2.209, 95.85]}
        rotation={[Math.PI, -0.09, Math.PI]}
        scale={[0.337, 0.197, 0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube086.geometry}
        material={materials.Material}
        position={[-2.473, 2.115, 91.495]}
        rotation={[0, 0.09, -Math.PI]}
        scale={[-0.149, -0.134, -0.149]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube087.geometry}
        material={materials.Material}
        position={[2.258, 4.623, 92.432]}
        rotation={[0, 0.09, -Math.PI]}
        scale={[-0.249, -0.101, -0.149]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube088.geometry}
        material={materials.Material}
        position={[-37.942, 3.38, 84.076]}
        rotation={[0, -0.309, -Math.PI]}
        scale={[-0.418, -0.319, -0.336]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube089.geometry}
        material={materials.Material}
        position={[-33.933, 4.8, 87.411]}
        rotation={[-Math.PI, 0.309, -Math.PI]}
        scale={[0.55, 0.146, 0.162]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube090.geometry}
        material={materials.Material}
        position={[-35.346, 4.97, 87.824]}
        rotation={[0, -0.309, -Math.PI]}
        scale={[-0.296, -0.079, -0.087]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube092.geometry}
        material={materials.Material}
        position={[-55.127, 0.798, 2.896]}
        rotation={[0, 0.988, 0]}
        scale={[1, 0.903, 1]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube093.geometry}
        material={materials.Material}
        position={[-44.547, 1.041, 2.523]}
        rotation={[Math.PI, -0.988, 0]}
        scale={[-0.405, -0.366, -0.405]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube094.geometry}
        material={materials.Material}
        position={[-43.412, 1.467, -1.815]}
        rotation={[Math.PI, -0.988, 0]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube095.geometry}
        material={materials.Material}
        position={[-42.398, 0.569, 3.804]}
        rotation={[0, 0.905, -Math.PI]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube096.geometry}
        material={materials.Material}
        position={[-50.358, 3.95, -0.217]}
        rotation={[0, 0.905, -Math.PI]}
        scale={[-0.345, -0.197, -0.219]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube098.geometry}
        material={materials.Material}
        position={[-64.267, 1.398, 27.087]}
        rotation={[Math.PI, -0.988, 0]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube099.geometry}
        material={materials.Material}
        position={[-71.212, 2.054, 28.685]}
        rotation={[0, 0.905, -Math.PI]}
        scale={[-0.345, -0.197, -0.219]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube100.geometry}
        material={materials.Material}
        position={[-63.083, 2.833, 14.254]}
        rotation={[0, 0.988, 0]}
        scale={[0.418, 0.319, 0.336]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube101.geometry}
        material={materials.Material}
        position={[-62.204, 2.536, 15.682]}
        rotation={[Math.PI, -0.988, 0]}
        scale={[-0.238, -0.19, -0.182]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube102.geometry}
        material={materials.Material}
        position={[-70.835, 1.133, 20.348]}
        rotation={[0, 0.988, 0]}
        scale={[0.337, 0.197, 0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube103.geometry}
        material={materials.Material}
        position={[-73.829, 4.15, 21.262]}
        rotation={[0, 0.988, 0]}
        scale={[0.337, 0.197, 0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube104.geometry}
        material={materials.Material}
        position={[-63.791, 2.115, 18.385]}
        rotation={[Math.PI, -0.988, 0]}
        scale={[-0.149, -0.134, -0.149]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube105.geometry}
        material={materials.Material}
        position={[-74.984, 4.623, 13.776]}
        rotation={[Math.PI, -0.988, 0]}
        scale={[-0.249, -0.101, -0.149]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube106.geometry}
        material={materials.Material}
        position={[-46.595, 3.38, -8.464]}
        rotation={[Math.PI, -0.988, 0]}
        scale={[-0.418, -0.319, -0.336]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube107.geometry}
        material={materials.Material}
        position={[-32.039, 4.8, -5.852]}
        rotation={[0, 0.139, 0]}
        scale={[0.55, 0.146, 0.162]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube108.geometry}
        material={materials.Material}
        position={[-30.944, 4.97, -6.836]}
        rotation={[Math.PI, -0.139, 0]}
        scale={[-0.296, -0.079, -0.087]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube110.geometry}
        material={materials.Material}
        position={[-69.183, 2.015, 55.555]}
        rotation={[-Math.PI, 0.925, -Math.PI]}
        scale={[1, 0.903, 1]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube111.geometry}
        material={materials.Material}
        position={[-77.742, 2.999, 41.297]}
        rotation={[Math.PI, -1.537, 0]}
        scale={[-0.896, -0.809, -0.896]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube112.geometry}
        material={materials.Material}
        position={[-73.963, 1.467, 48.388]}
        rotation={[0, -0.925, -Math.PI]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube113.geometry}
        material={materials.Material}
        position={[-68.33, 4.399, 49.32]}
        rotation={[-Math.PI, 1.008, 0]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube114.geometry}
        material={materials.Material}
        position={[-74.791, 3.95, 55.466]}
        rotation={[-Math.PI, 1.008, 0]}
        scale={[-0.345, -0.197, -0.219]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube115.geometry}
        material={materials.Material}
        position={[-44.179, 2.015, 84.924]}
        rotation={[0, -0.646, 0]}
        scale={[0.928, 0.749, 0.841]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube116.geometry}
        material={materials.Material}
        position={[-53.746, 1.398, 77.739]}
        rotation={[0, -0.925, -Math.PI]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube117.geometry}
        material={materials.Material}
        position={[-54.574, 3.881, 84.818]}
        rotation={[-Math.PI, 1.008, 0]}
        scale={[-0.345, -0.197, -0.219]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube118.geometry}
        material={materials.Material}
        position={[-65.436, 2.833, 72.313]}
        rotation={[-Math.PI, 0.925, -Math.PI]}
        scale={[0.418, 0.319, 0.336]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube120.geometry}
        material={materials.Material}
        position={[-76.065, 3.745, 70.49]}
        rotation={[-Math.PI, 0.925, -Math.PI]}
        scale={[0.908, 0.531, 0.588]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube121.geometry}
        material={materials.Material}
        position={[-62.445, 2.137, 84.789]}
        rotation={[-Math.PI, 0.925, -Math.PI]}
        scale={[0.337, 0.197, 0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube122.geometry}
        material={materials.Material}
        position={[-61.783, 2.115, 74.368]}
        rotation={[0, -0.925, -Math.PI]}
        scale={[-0.346, -0.134, -0.279]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube123.geometry}
        material={materials.Material}
        position={[-69.884, 4.623, 83.362]}
        rotation={[0, -0.925, -Math.PI]}
        scale={[-0.249, -0.101, -0.149]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube124.geometry}
        material={materials.Material}
        position={[-81.294, 3.38, 49.152]}
        rotation={[0, -0.925, -Math.PI]}
        scale={[-0.418, -0.319, -0.336]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube125.geometry}
        material={materials.Material}
        position={[-85.798, 4.8, 56.738]}
        rotation={[-Math.PI, 0.925, -Math.PI]}
        scale={[0.55, 0.146, 0.162]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube126.geometry}
        material={materials.Material}
        position={[-87.19, 4.97, 56.258]}
        rotation={[0, -0.925, -Math.PI]}
        scale={[-0.296, -0.079, -0.087]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/clouds2.glb");
