/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model() {
  const { scene } = useGLTF("/1.glb");
  return <primitive object={scene} />;
}
useGLTF.preload("/1.glb");
