/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/clouds.glb");
  const [material, setMaterial] = useState();
  const groupRef = useRef();

  useFrame(({ clock }) => {
    const elapsedTime = clock.getElapsedTime();
    if (groupRef.current) {
      groupRef.current.position.x = Math.sin(elapsedTime * 0.2) * 10;
    }
  });

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube002.geometry}
        // material={{ ...materials.Material, transparent: true, opacity: 0.8 }}
        position={[16.034, 0.915, 0]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube001.geometry}
        position={[21.227, 2.015, -3.831]}
        scale={[1, 0.903, 1]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube003.geometry}
        position={[16.706, 1.041, 0.246]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.405, -0.366, -0.405]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube004.geometry}
        position={[20.952, 1.467, -1.194]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube005.geometry}
        position={[16.819, 0.569, 2.745]}
        rotation={[0, -0.083, -Math.PI]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube006.geometry}
        position={[15.796, 3.95, -6.114]}
        rotation={[0, -0.083, -Math.PI]}
        scale={[-0.345, -0.197, -0.219]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube007.geometry}
        position={[-25.89, 2.015, -4.451]}
        rotation={[-Math.PI, 0.004, -Math.PI]}
        scale={[0.928, 0.749, 0.841]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube008.geometry}
        position={[-14.656, 1.398, -2.7]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.218, -0.197, -0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube009.geometry}
        position={[-19.812, 3.881, -7.619]}
        rotation={[0, -0.083, -Math.PI]}
        scale={[-0.345, -0.197, -0.219]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube010.geometry}
        position={[-3.29, 2.833, -8.775]}
        scale={[0.418, 0.319, 0.336]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube011.geometry}
        position={[-3.998, 2.536, -7.254]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.238, -0.19, -0.182]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube012.geometry}
        position={[-12.644, 3.638, -11.893]}
        scale={[0.337, 0.197, 0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube013.geometry}
        position={[-15.055, 4.15, -13.89]}
        scale={[0.337, 0.197, 0.218]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube014.geometry}
        position={[-7.129, 2.115, -7.092]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.149, -0.134, -0.149]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube015.geometry}
        position={[-9.441, 4.623, -18.974]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.249, -0.101, -0.149]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube016.geometry}
        position={[24.752, 3.38, -7.511]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.418, -0.319, -0.336]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube017.geometry}
        position={[21.401, 4.8, -15.672]}
        scale={[0.55, 0.146, 0.162]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube018.geometry}
        position={[22.621, 4.97, -16.496]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.296, -0.079, -0.087]}
      >
        <meshPhysicalMaterial
          ref={setMaterial}
          color="white"
          transparent
          opacity={0.5}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/clouds.glb");
