/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/dreamscene.glb");
  const [material, setMaterial] = useState();
  return (
    <group {...props} dispose={null}>
      <group
        position={[-7.151, 2.461, 5.939]}
        rotation={[0, -0.863, 0]}
        scale={[0.941, 2.167, 0.941]}
      >
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.Brown} />
        <mesh
          geometry={nodes.Cylinder_2.geometry}
          material={materials["Green Petal"]}
        />
        <mesh
          geometry={nodes.Cylinder_3.geometry}
          material={materials["Light Green Petal"]}
        />
      </group>
      <group
        position={[-11.184, 1.811, 7.569]}
        rotation={[0, 0.258, 0]}
        scale={[0.941, 1.627, 0.941]}
      >
        <mesh
          geometry={nodes.Cylinder007.geometry}
          material={materials.Brown}
        />
        <mesh
          geometry={nodes.Cylinder007_1.geometry}
          material={materials["Green Petal"]}
        />
        <mesh
          geometry={nodes.Cylinder007_2.geometry}
          material={materials["Light Green Petal"]}
        />
      </group>
      <group
        position={[-8.932, 0.35, 9.17]}
        rotation={[-0.023, -0.871, 0.058]}
        scale={0.304}
      >
        <mesh geometry={nodes.Icosphere.geometry} material={materials.Yellow} />
        <mesh
          geometry={nodes.Icosphere_1.geometry}
          material={materials["Green Petal"]}
        />
        <mesh
          geometry={nodes.Icosphere_2.geometry}
          material={materials["Light Green Petal"]}
        />
        <mesh
          geometry={nodes.Icosphere_3.geometry}
          material={materials.Purple}
        />
        <mesh
          geometry={nodes.Icosphere_4.geometry}
          material={materials["Purple 2"]}
        />
        <mesh
          geometry={nodes.Icosphere_5.geometry}
          material={materials.Grass}
        />
      </group>
      <group
        position={[-7.39, 0.381, 8.278]}
        rotation={[-3.069, -1.368, -2.996]}
        scale={0.304}
      >
        <mesh
          geometry={nodes.Icosphere005.geometry}
          material={materials.Orange}
        />
        <mesh
          geometry={nodes.Icosphere005_1.geometry}
          material={materials["Green Petal"]}
        />
        <mesh
          geometry={nodes.Icosphere005_2.geometry}
          material={materials["Light Green Petal"]}
        />
        <mesh
          geometry={nodes.Icosphere005_3.geometry}
          material={materials.Blue}
        />
        <mesh
          geometry={nodes.Icosphere005_4.geometry}
          material={materials["Blue 2"]}
        />
        <mesh
          geometry={nodes.Icosphere005_5.geometry}
          material={materials.Grass}
        />
      </group>
      <group
        position={[420.268, 4.462, 224.38]}
        rotation={[0, 0.624, 0]}
        scale={[2.584, 1.09, 2.148]}
      >
        <mesh
          geometry={nodes.Torus009.geometry}
          material={materials["Light Green Petal"]}
        />
        <mesh geometry={nodes.Torus009_1.geometry} material={materials.Brown} />
        <mesh
          geometry={nodes.Torus009_2.geometry}
          material={materials["Green Petal"]}
        />
      </group>
      <group
        position={[486.721, 4.316, -187.355]}
        rotation={[0.303, -0.287, 1.103]}
        scale={[1.768, 19.136, 1.768]}
      >
        <mesh
          geometry={nodes.Cylinder023.geometry}
          material={materials["Grey 2"]}
        />
        <mesh
          geometry={nodes.Cylinder023_1.geometry}
          material={materials.Grey}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials["Grey 2"]}
        position={[481.17, 0.523, -178.924]}
        rotation={[-2.615, 0.385, 1.964]}
        scale={[1.768, 19.136, 1.768]}
      />
      <group
        position={[490.42, 4.426, -183.574]}
        rotation={[-2.615, 0.385, 1.964]}
        scale={[1.768, 28.683, 1.768]}
      >
        <mesh
          geometry={nodes.Cylinder031.geometry}
          material={materials["Grey 2"]}
        />
        <mesh
          geometry={nodes.Cylinder031_1.geometry}
          material={materials.Grey}
        />
      </group>
      <group
        position={[504.394, 4.374, -172.829]}
        rotation={[0.303, -0.287, 1.103]}
        scale={[1.768, 19.136, 1.768]}
      >
        <mesh
          geometry={nodes.Cylinder032.geometry}
          material={materials["Grey 2"]}
        />
        <mesh
          geometry={nodes.Cylinder032_1.geometry}
          material={materials.Grey}
        />
      </group>
      <group
        position={[12.928, 0.897, 1.526]}
        rotation={[-0.294, 1.281, 0.424]}
        scale={[0.69, 0.616, 0.798]}
      >
        <mesh
          geometry={nodes.Plane097.geometry}
          material={materials["Light Green Petal"]}
        />
        <mesh
          geometry={nodes.Plane097_1.geometry}
          material={materials["Green Petal"]}
        />
      </group>
      <mesh
        geometry={nodes.Plane005.geometry}
        material={materials["Blue.001"]}
        position={[85.708, 10.446, -389.67]}
        rotation={[0.404, 0.492, 0.136]}
        scale={[76.586, 100.143, 59.549]}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={materials["Blue.001"]}
        position={[-13.925, 30.599, -461.174]}
        rotation={[0.404, 0.492, 0.136]}
        scale={[41.01, 51.299, 41.424]}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={materials["Blue.001"]}
        position={[-496.931, 19.822, -593.922]}
        rotation={[0.416, -0.474, -0.098]}
        scale={[115.831, 133.843, 125.931]}
      />
      <group
        position={[0, 0.322, 13.417]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[30.774, 61.548, 40.562]}
      >
        <mesh geometry={nodes.Plane005_1.geometry}>
          <meshPhysicalMaterial
            ref={setMaterial}
            color="#D7D792"
            metalness={0.4}
            roughness={0.8}
          />
        </mesh>
        <mesh geometry={nodes.Plane005_2.geometry}>
          <meshPhysicalMaterial
            ref={setMaterial}
            color="#40884A"
            metalness={0.4}
            roughness={0.8}
          />
        </mesh>
      </group>
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials.Ocean}
        position={[0, -0.006, 0]}
        scale={57.766}
        visible={false}
      />
      <group
        position={[1.303, 0.436, -16.505]}
        rotation={[-2.873, 1.254, 3.028]}
        scale={[0.69, 0.616, 0.798]}
      >
        <mesh geometry={nodes.Plane007_1.geometry} material={materials.Blue} />
        <mesh
          geometry={nodes.Plane007_2.geometry}
          material={materials["Blue.001"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials.Grass}
        position={[442.308, -9.361, -403.126]}
        scale={[30.144, 20.466, 20.466]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials.Grass}
        position={[422.331, -1.568, 236.6]}
        rotation={[Math.PI, -0.897, Math.PI]}
        scale={[11.484, 7.797, 7.797]}
      />
    </group>
  );
}

useGLTF.preload("/dreamscene.glb");
