/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("models/scene.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Suzanne007.geometry}
        material={nodes.Suzanne007.material}
        position={[1.742, 1.044, 24.966]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Suzanne.geometry}
        material={nodes.Suzanne.material}
        position={[-0.083, 2.121, -11.686]}
      />
    </group>
  );
}

useGLTF.preload("/scene.glb");
